import './globals.css';
import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import SmoothLenis from '@/components/smoothLenis';
import TransitionProvider from '@/context/transitionContext';

const geistMono = JetBrains_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistMono.variable} select-none antialiased`}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </head>
      <body className="font-mono md:px-9">
        {/* Overlay global for transitions */}
        <div className="page-transition fixed top-0 left-0 flex pointer-events-none w-screen h-screen opacity-1 z-50">
          <div className="box relative flex-1 top-[100%] bg-[--foreground]"/>
          <div className="box relative flex-1 top-[100%] bg-[--foreground]"/>
          <div className="box relative flex-1 top-[100%] bg-[--foreground]"/>
          <div className="box relative flex-1 top-[100%] bg-[--foreground]"/>
          <div className="box relative flex-1 top-[100%] bg-[--foreground]"/>
        </div>
        <TransitionProvider>
          <SmoothLenis>
            {children}
          </SmoothLenis>
        </TransitionProvider>
      </body>
    </html>
  );
}
